export const COLLAPSED_MAX_HEIGHT = 220;

export const SYSTEM_HINT_THRESHOLD = 50;

export const TOOLTIP_COPY = {
  input: 'Input tokens — context sent to the model for this turn',
  output: 'Output tokens — text generated by the model in this turn',
  hint: 'Includes system prompt tokens — Claude Code injects its full instructions on the first message of every run',
} as const;
